### ISSUE TITLE
Sort Vocabulary by recently added/modified

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#102]
The Vocabulary page currently displays symbols alphabetically. If it had a "sort by date" option, visitors could see the most recently added/updated symbols first if they so desired.

This is not a high priority but would be nice to have if it's easy.

**Comment by toolness** [comment]
Hmm, this isn't actually super-straightforward because [git intentionally doesn't set the file's last created/modified timestamp](https://stackoverflow.com/questions/2179722/checking-out-old-file-with-original-create-modified-timestamps).  That means that any code that tried to take their files' created/modified timestamps into account wouldn't behave consistently... in order to work consistently, we'd need to actually delve into the git commit history and examine when a file was created and/or changed, which is definitely possible but not particularly quick and easy to implement. 😣

**Comment by ninapaley** [comment]
@toolness Then I'm gonna close this sucker!
