### ISSUE TITLE
Social Media Posting Bot

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#123]
A bot that generates an image and posts it to twitter, fecebook, neenster.org, and wherever else we want. Posts would include a link to mysticsymbolic.art and/or https://www.gofundme.com/f/mysticsymbolic-development .

I knew this was something we were gonna do in the future, but @mittimithai notes we could do it now. Would certainly help with fundraising!

**Comment by webaissance** [comment]
@mittimithai is working on this!
On June 22, 2021 wrote:
Bot(s) are up:
https://github.com/mittimithai/mysticsymbot

Which posts to:
https://twitter.com/MSymbot
mysticsymbot on neenster and botsinspace fedi instances
I'm just fiddling to get the auth keys from fb (not as easy as twitter) for a mysticsymbot fb group (already created)

I am using APIs to post, but I started with selenium (writing the selenium was easier than writing my 200 character essays to twitter). WIll be useful for pulling from the website directly.
I'll setup nina with the keys etc. soon.  Current it takes a manually curated list of images (with titles), posts the top one and logs what it is posted.

Will be seeing if colors can be improved next (I have an idea based on essentially maximising one contrast while minimizing another...)

**Comment by toolness** [comment]
Nice thanks for the update @webaissance and @mittimithai! 

BTW @webaissance when you post the words of someone else, can you prefix what they've said with a greater-than sign followed by a space (`> `)? That way it will show up as you "quoting" them which is easier to read, e.g. without the `> ` it looks like:

Do this thing!

but with the  `> ` it looks like:

> Do this thing!

It just makes it easier to understand that the words are someone else's and not your own (otherwise reading your comment above it might look like _you're_ using APIs to post, rather than @mittimithai).
