### ISSUE TITLE
Support for "reflected" gradients

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#137]
Moho has "reflected" as a gradient option (like linear but reflected in both directions), which I used in bone.svg and this banner.svg:
![banner](https://user-images.githubusercontent.com/79212762/120019597-43f0c780-bfae-11eb-95b9-bcc22f74c5ff.png)
But in MysticSymbolic it renders as a regular linear gradient, so the gray is only on one half of the center:
![Screen Shot 2021-05-28 at 12 20 48 PM](https://user-images.githubusercontent.com/79212762/120020326-2a03b480-bfaf-11eb-994d-ed896cef0461.png)

If this can be fixed without too much trouble, please do so. But if it requires significant work, it's not worth it right now! Other tasks take priority.

**Comment by toolness** [comment]
Hmm, I'm looking at the [`banner.svg`](https://github.com/mysticsymbolic/mysticsymbolic.github.io/blob/main/assets/symbols/banner.svg) file and it seems like it has the same problem...

In general, if you open the SVG that Moho exports in a browser and it doesn't look the same way that it does in Moho, then unfortunately it's not something I can fix. 😞   I can only fix the situations where the exported SVG looks fine but it doesn't look right in the program, alas.

This is a bummer that I've seen in some other programs too--the thing will look really cool in the art program, but then when you export it to SVG, certain really cool effects are lost.  I think this is because of limitations in the SVG format... For example, as far as I know, SVG doesn't have a concept of a "reflected" gradient, it only has linear and radial, so perhaps this is why reflected gradients don't look right when exported to SVG.

**Comment by ninapaley** [comment]
Not a problem, I can work around it. I shall close this one!
