### ISSUE TITLE
Can gradients be "turned off"?

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#140]
Someone on fecebook asked this: "Is it possible to turn them off?....Never liked gradients."

IS it possible to turn them off? Toggle a switch, and the gradient fill turns to standard (usually specified as white) solid fill color? If it is possible without too much work, please consider this a request.

**Comment by toolness** [comment]
Heh, that's funny, I was actually wondering the same thing--I like the gradients, but I also liked the "flat" look before they arrived, and I thought it might be nice to be able to toggle them...

I think it should be possible, especially if we default all gradients to be solid white.  Another thing we could try doing is analyzing the gradient itself: if more than 50% of it appears to be either white or black, we just force the whole thing to be entirely that color.

One thing to consider is what happens if there are gradients that _don't_ include white or black, e.g. a gradient that's kind of like the rainbow symbol, where it has colors completely separate from fill/stroke.  Should _those_ gradients be "flattened" too?  Or only gradients that use stroke/fill somewhere in them?

**Comment by ninapaley** [comment]
If defaulting all gradients to solid white is the easiest, lowest-hanging fruit, I say do that. Easiest is best. I have used solid black for some fills, such as the tree trunks; solid black should stay black. But wherever there is a gradient, even if it doesn't have a stroke, filling with solid white should work.

> One thing to consider is what happens if there are gradients that _don't_ include white or black, e.g. a gradient that's kind of like the rainbow symbol, where it has colors completely separate from fill/stroke. Should _those_ gradients be "flattened" too? Or only gradients that use stroke/fill somewhere in them?

The rainbow symbol is unique. I say it shouldn't be flattened; it should always be its colorful self.

**Comment by toolness** [comment]
Ok sounds good!

Hmm, are there actually any symbols that use non-fill/stroke (i.e. non-black/white) colors in gradients yet?  Aside from #138, which featured an accidental use of near-black?  I don't _think_ the rainbow uses a gradient (it was working before I added support for gradients, at least) and if you don't have any plans to make uniquely-colored gradients anytime in the near future, then I don't need to worry about accidentally "flattening" them (adding logic to detect for gradients that shouldn't be flattened will take extra work).

**Comment by ninapaley** [comment]
Other than the rainbow, the only non black/white symbols are errors on my part. There may still be some hidden about; if you ever find any please let me know so I can fix.
The rainbow does not use a gradient, it's just bands of solid fills.

**Comment by toolness** [comment]
Ok I think I fixed this in #148!
