### ISSUE TITLE
SVGs made with Affinity Designer

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#144]
Hey @toolness ,

I noticed Moho was rendering some radial gradients strangely, especially on the "hill" symbol. I tried everything in that program, and even though it rendered PNGs correctly, the SVGs were often weird. So I paid all of $25 for Affinity Designer to try to make correct PNGs from there. I exported the symbol "specs" arrows and square as SVG from Moho and imported them to Designer, in hopes their exact configurations and colors would remain the same. Then I "grouped" them in Designer, which put them all into a single layer I named "specs." I uploaded the resultant "hill_BWgradient_AD.svg" into the symbols folder, and got a big ol red-X fail. Can you please examine the attached compressed SVG and suggest what to change/fix so it'll work?
[hill_BWgradient_AD.svg.zip](https://github.com/mysticsymbolic/mysticsymbolic.github.io/files/6588094/hill_BWgradient_AD.svg.zip)

**Comment by toolness** [comment]
Er, so unfortunately, supporting this will take a lot of work, because Affinity Designer is saving SVGs in very different ways than Moho does.

The really unfortunate thing about this, more generally, is that our SVG importer, as it currently exists, is quite tightly coupled to Moho's way of saving SVGs in particular: aside from not being able to use Affinity Designer, it's also quite likely that we can't easily use SVG exports from other popular art programs like Inkscape, Krita, Illustrator, Figma, and so forth.  This is a bummer, especially when it comes to allowing users to submit their own symbols.  Or worse, were Moho to release a new version that changed how it exported SVGs, we'd likely have to either require that you use the old verison, or spend a lot of time adapting the SVG importer to be able to import the new one's SVGs. 😞

For now I've removed the Affinity Designer SVGs in f2553177a9d3d23723959c976479f8897baf5300.

**Comment by ninapaley** [comment]
Thanks for investigating.

Are you able to generate any gradients yourself? To fix the "hill" it just needs a circular radial gradient centered on the bottom line. It should look like this:
![hill](https://user-images.githubusercontent.com/79212762/120896580-df55ee00-c5e7-11eb-8395-a6d221f15fcf.png)
