### ISSUE TITLE
import "./style.css" not working

### ISSUE THREAD

**Issue by webaissance** [mysticsymbolic/mysticsymbolic.github.io#164]
I want to import different CSS into different pages. A few versions back I could import "./style.css" and the styles would apply.
Now it doesn't work and I can't track down why.
I'm guessing that the modules that were being used to do that were removed because of vulnerabilities?
I'd like to be able to have different CSS styles on different pages without having to alter /dist/index.html
Any ideas appreciated.  @toolness ? Thanks!

**Comment by toolness** [comment]
Ohh this is probably because we used to use [Parcel](https://parceljs.org/) to bundle everything together, but as of #131 we use [esbuild](https://esbuild.github.io/) (see that PR for the rationale).

According to [esbuild's documentation](https://esbuild.github.io/content-types/#css), it looks like it _does_ support CSS imports, but it's going to bundle everything together into a new file--I am guessing it will likely be called `browser-main.css` but I'm not sure.  Our `index.html` doesn't currently import that file...  Can you see if it's generated, and if so, add a `<link>` tag to the `index.html` that points to it?

**Comment by webaissance** [comment]
Thanks @toolness  I will check on that....

**Comment by webaissance** [comment]
I found an article that explains how to use different CSS for each view - using Helmet! It works well. I implemented it in upcoming Draft Pull Request
https://www.pluralsight.com/guides/how-to-create-single-page-reactjs-page-app-different-css-each-view
Thanks for the help with this.

**Comment by toolness** [comment]
Oh cool... Hmm, I think I like just using `import` better though, since it's only one line, while using Helmet requires more JSX, and because the CSS is loaded asynchronously, it might result in a [flash of unstyled content](https://en.wikipedia.org/wiki/Flash_of_unstyled_content)...

All that needs to be done is for the `index.html` to load the CSS file that Parcel is building, do you think you could try that and see if it works?

**Comment by toolness** [comment]
Hey @webaissance, I just fixed this in #206 so you should be able to import CSS files in your TS/TSX now!

**Comment by webaissance** [comment]
Thanks @toolness ! Sorry - I hadn't seen your earlier request from June 26 "do you think you could try that and see if it works?" 
I try to catch all the comments as they come int...
Glad this is working again.
