### ISSUE TITLE
"neutral" attachment arrows

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#187]
On symbol specs we have color-coded arrows for "tail", "legs", "arm", "horns", and "crown." I am now going through every symbol's TOML to specify what it should attach_to. BUT what if we had another arrow, of another color, that would override all that, and allow anything to attach to it, regardless of its attach_to restrictions? I'm specifically thinking of this:
![EmperorSpecs](https://user-images.githubusercontent.com/79212762/123427263-0457d400-d58a-11eb-857b-119aea4d3679.png)
The arrows next to the Emperor are currently green "wings". But ideally they wouldn't be restricted to only symbols that attach_to "wings". Ideally they would even pick from symbols that `attach_to = []` . Right now, if I used any of the existing color arrows, they would restrict some symbols.
If I made a new arrow colored, say, DE9C78 (or, since it's on the "specs" layer, could the neutral color be black or white?), could it pick from all symbols regardless of attach_to status?

**Comment by ninapaley** [comment]
@toolness An alternative to this would be a "bonkers mode" toggle option that would just override all the TOML attachment restrictions.

**Comment by toolness** [comment]
Ah interesting!  The new arrow color could indeed be black or white since it's on the specs layer... I kind of like the idea of it being one of those colors because they can represent the combination of (or absence of) all colors, which kinda thematically fits what the attachment point type is about, hehe.

Bonkers mode is also possible but if I'm interpreting you correctly, it's less flexible than adding a new attachment point type since it would apply to _all_ attachment points, right?  So you couldn't e.g. say that the crown point on the Emperor is still a crown attachment point and that only the wings are bonkers.  Regardless though, I think bonkers mode is worth exploring _in addition to_ the concept of neutral attachment points--it could be a fun way to break all the rules and see what kinds of truly weird compositions are generated...

Anyhow, yet another option might be to actually address this through the TOML.  If we have a new option like this:

```
attach_anything_to = ["arm"]
```

and added that to the Emperor's TOML, then it could effectively mean "for the arm attachment points on this symbol, attach _anything_ to them, not just what we think of as appropriate for arms."

One thing I like about this approach is that it means making these tweaks doesn't require Moho (or the hand-editing of SVG files, which can be a pain).  But I think any of these solutions should be possible...

**Comment by ninapaley** [comment]
Great! I will make the "neutral" arrows BLACK. 
>One thing I like about this approach is that it means making these tweaks doesn't require Moho (or the hand-editing of SVG files, which can be a pain). But I think any of these solutions should be possible...

I would much rather hand-edit the image in Moho than type lines of text in TOMLs! So adding black arrows is my preference over `attach_anything_to = ["arm"]` . But maybe if someone else wants to edit that way, we could have both options?

"Bonkers Mode" is basically what we've had thus far. I am now breaking that by specifying `attach_to` in all the TOMLs (although some still `attach_to` everything). If it's easy to implement, a Bonkers Mode toggle would just turn that off globally.

**Comment by toolness** [comment]
Oh ok that makes sense, BLACK it is!  Although I forget if the build process will explode if it finds an arrow color it doesn't recognize, or if it just logs it as a warning... so maybe give me time to add support for this before you start adding black arrows?  Or alternatively I guess you could just try it out on a PR branch and see if it explodes, hehe.

Bonkers mode sounds good--do you think you can file a separate issue about Bonkers mode?  That way I can tackle these two things separately and close them individually.

**Comment by ninapaley** [comment]
Here is a test symbol with both black attachment arrows AND star trek arrow shapes. Let me know if they work!
[skeleton_test.svg.zip](https://github.com/mysticsymbolic/mysticsymbolic.github.io/files/6720129/skeleton_test.svg.zip)
