### ISSUE TITLE
Limit Randomized Mandala Radii

### ISSUE THREAD

**Issue by ninapaley** [mysticsymbolic/mysticsymbolic.github.io#76]
I believe if the Radius is limited to between +100 and +500, we will get better results on randomly generated mandalas. 
Can the sliders stay as they are, with the limits only applied to the "randomize!" function?

Also, minimum number of symbols on a mandala should be 2. If we're going to have just one, it should be centered over the central vertex, rather than sitting on the circumference.

**Comment by ninapaley** [comment]
(and if you have time for a hand-holding lesson later today, @toolness , I'd love to learn how to go in and make small adjustments like these. I should be free from 6pm - 9pm EDT tonight.)

**Comment by toolness** [comment]
Oof, so this actually isn't something you can easily change right now, because the architecture of the code is structured in a way that doesn't allow the randomization range to deviate from the slider range.  I'll have to add that capability to the architecture first, and from there on out, it should be easier to make changes like this!
